---
title: "US babynames"
author: "Zelvy Fauzan"
date: "2026-07-24"
output: html_document
---

## 1. Introduction

This is a part of my journey in revisiting the DataCamp's Data Analyst in R career track. It's an initiative of exploratory data analysis rather than a follow-along instruction.

The dataset used in this project is the babynames dataset from the USA social security administration.

This dataset is available as a package (namely, babynames) under the CRAN repository but I decided to take some detour. What I mean by that is that instead of starting from the CSV, I decided to make it simulate an import from DBMS. This way, I can also hone my data import skill.

### 1.1. Environment Setup

Some of the technologies I used in this projects are:

* [R language](https://www.r-project.org/)
* [RStudio](https://posit.co/downloads)
* [PostgreSQL](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads)
* [pgAdmin 4](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) (I downloaded the bundle version to save up some hassles).


### 1.2. Procedures

I skipped entailing the installation process of the said technologies and assume enyone who wanted to replicate this project have already installed all of them. So, I only elaborate the data import procedures.

1. Download the [babyname dataset from Kaggle](https://www.kaggle.com/datasets/kaggle/us-baby-names?resource=download).
2. Create a new Schema for the project in pgAdmin 4. I used the name "babyname-project"
3. Import the CSVs

```{r setup1}

```

To Do:
1. See what's the most popular name in the US over the year.
2. See what's the most popular name for each gender in the US over the year.
3. The timeline of the latest popular name for each gender.
